### ISSUE TITLE
await on an already resolved Promise seems to hang, when the value is null

### ISSUE THREAD

**Issue by P-Treiber** [onehilltech/promises#5]
I encountered a problem, where the await seems to hang.

We had a function which returned Promise.resolve(null), and sometimes our app did not continue execution afterwards. Unfortunately, this behavior is not reproducible deterministically, but changing the Promise.resolve(null) to Promise.resolve("Success") fixed our problems.

From a look at the source code of the AwaitHandler and the implementation of await, it looks like this could happen sometimes:

If the promise is already resolved, AwaitHandler.onResolved will be called, and therefore the isSettled condition is signaled. If this happens before AwaitHandler.await is called, the await will check whether the value is null. Since the promise is resolved with null, the AwaitHandler assumes that the Promise is not yet resolved and waits for the condition to be signaled, which will not happen any more.

Am I right that this can happen? Unfortunately, I was not able to write a simple test which shows the behavior.

**Comment by hilljh82** [comment]
@P-Treiber I did a quick check and your analysis is correct. This situation can occur. I fixed a similar issue after the `await()` method is called and the promise settles to `null`.

I will work on a fix for this issue.

**Comment by P-Treiber** [comment]
Ok, thanks!

**Comment by hilljh82** [comment]
@P-Treiber I have created a fix for this issues and released a new patch 0.10.3. Please let me know if this patch resolves the problem you are experiencing.

**Comment by P-Treiber** [comment]
@hilljh82 Thank you for the patch. It fixes our issues. You can close the issue.
