### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by paulvi** [onehilltech/promises#7]
Development has stopped here since Feb 2019

On demand GitHub repositories build with https://jitpack.io is cool, but most Java developers check version on site like 
https://mvnrepository.com e.g. https://mvnrepository.com/artifact/com.onehilltech.promises/promises-jvm
And `onehilltech.promises` is just not findable/ not avaible in Spring Libs repo.

Please recommend any similar or alternative projects.

**Comment by hilljh82** [comment]
@paulvi The project is not abandoned. At the moment, there has been no need to any additional features.

**Comment by paulvi** [comment]
OK

maybe then just close all outstanding issues
